### ISSUE TITLE
Sidebars Switch Places 

### ISSUE THREAD

**Issue by jaysonjaynes** [ucsf-web-services/ucsf_base#1] opened 2014-08-28 17:19 UTC
In the smallest screen size, sidebar-first switches places with sidebar-second in order. 
![screen shot 2014-08-28 at 10 17 02 am](https://cloud.githubusercontent.com/assets/2229010/4079630/5d67816e-2ed7-11e4-9d4d-77bf3d2bb452.png)
![screen shot 2014-08-28 at 10 18 14 am](https://cloud.githubusercontent.com/assets/2229010/4079634/677c13cc-2ed7-11e4-9be9-8964617b4a90.png)

**Comment by stopfstedt** [comment] 2014-09-02 18:26
so this seems to be intentional:

https://github.com/ucsf-drupal/ucsf_base/blob/7.x-1.0/js/script.js#L211

**Comment by stopfstedt** [comment] 2014-09-02 18:27
"Its a feature, not a bug".

@johnkealy, any recollections as to why this column swap occurs?

**Comment by riberi** [comment] 2014-09-02 18:31
Hi to both of you.
I'm one of the devs who initially worked on the install profile.
If I can give you some insights, it's because the right sidebar usually has some content related to the main area (for example callout boxes), while the left sidebar is the menu.
On resize, you don't really want the menu to split those two sections. That's why we pushed the menu after the rest.

Let me know if that doesn't make sense.

**Comment by johnkealy** [comment] 2014-09-02 18:34
@riberi Anthony thanks for commenting!

**Comment by stopfstedt** [comment] 2014-09-02 18:34
@riberi, thanks for the info.

**Comment by riberi** [comment] 2014-09-02 18:36
@stopfstedt @johnkealy Sure! No problem!
Ping me anytime if you need explanations about anything in the install profile!

**Comment by stopfstedt** [comment] 2014-09-02 18:40
ok, will see if i can refactor this code to make this `update_resizables` function overridable, e.g. by defining it as as member of the `Drupal.behaviors.ucsf` namespace object.

That way, we can leave this as-is in the base theme, and @jaysonjaynes may be able to replace it with an empty function in his sub-theme to prevent the switcheroo.

**Comment by riberi** [comment] 2014-09-02 18:45
Yep definitely! Good idea.
I wish we had more time back in the days to polish everything up.

**Comment by jaysonjaynes** [comment] 2014-09-02 18:45
Thanks, @stopfstedt and @riberi. I get how you might want to do this to place related resources above the menu, but we aren't using it that way, and want to change the behavior. Thanks for making that possible, Stefan.

**Comment by stopfstedt** [comment] 2014-09-02 21:07
fixed by #3.

**Closed as completed by stopfstedt** 2014-09-02 21:07 UTC
